[package]
name = "rustedserver"
version = "0.1.0"
authors = ["Rafael Fillipe Silva <silva.rafaelfillipe@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["blocking", "macros", "rt-core", "rt-threaded"] }