# Combat settings
# NOTE: valid values for world_type are: "pvp", "no-pvp" and "pvp-enforced"
[combat]
world_type = "pvp"                    #("pvp" or "no-pvp" or "pvp-enforced")
hotkey_aimbot_enabled = true          #(true or false)
protection_level = 1                  #(>=0)
kills_to_red_skull = 3                #(>0 or 0)
kills_to_black_skull = 6              #(>0 or 0)
pz_locked = 60000                     #(>=0) seconds
remove_charges_from_runes = true      #(true or false)
remove_charges_from_potions = true    #(true or false)
remove_weapon_ammunition = true       #(true or false)
remove_weapon_charges = true          #(true or false)
time_to_decrease_frags = 86400        #(>=0 or -1) seconds [24 * 60 * 60]
white_skull_time = 900                #(>=0 or -1) seconds [15 * 60]
stair_jump_exhaustion = 2000          #(>=0) seconds
experience_by_killing_players = false #(true or false)
exp_from_players_level_range = 75     #(>=0)

# Connection Config
# NOTE: max_players set to 0 means no limit
[connection]
ip = "127.0.0.1"                          #(ip)
bind_only_global_address = false          #(true or false)
login_protocol_port = 7171                #(0 - 65535)
game_protocol_port = 7172                 #(0 - 65535)
status_protocol_port = 7171               #(0 - 65535)
max_players = 0                           #(>0 or 0)
motd = "Welcome to The Forgotten Server!" #(text)
one_player_online_per_account = true      #(true or false)
allow_clones = false                      #(true or false)
server_name = "Forgotten"                 #(text)
status_timeout = 5000                     #(>=0)
replace_kick_on_login = true              #(true or false)
max_packets_per_second = 25               #(>=0)

# Deaths
# NOTE: Leave death_lose_percent as -1 if you want to use the default
# death penalty formula. For the old formula, set it to 10. For
# no skill/experience loss, set it to 0.
[death]
death_lose_percent = -1 #(>=0 or -1)

# Houses
# NOTE: set house_price_each_sqm to -1 to disable the ingame buy house functionality
[housing]
house_price_each_sqm = 1000    #(>=0 or -1)
house_rent_period = "never"    #("yearly" or "monthly" or "weekly" or "daily" or "never")
house_owned_by_account = false #(true or false)
house_door_show_price = true   #(true or false)

# Item Usage
[item_usage]
time_between_actions = 200     #(>=0)
time_between_ex_actions = 1000 #(>=0)

# Map
# NOTE: set map_name WITHOUT .otbm at the end
[map]
map_name = "forgotten" #(filename[without .otbm])
map_author = "Komic"   #(text)

# Market
[market]
market_offer_duration = 2592000               #(>=0) seconds [30 * 24 * 60 * 60]
premium_to_create_market_offer = true         #(true or false)
check_expired_market_offers_each_minutes = 60 #(>0 or 0) minutes [60]
max_market_offers_at_a_time_per_player = 100  #(>0 or 0)

# MySQL
[sql]
mysql_host = "127.0.0.1"       #(ip or hostname)
mysql_user = "forgottenserver" #(text)
mysql_pass = ""                #(text)
mysql_db = "forgottenserver"   #(database name)
mysql_port = 3306              #(0 - 65535)
mysql_conn = 10                #(>0)

# Misc.
# NOTE: classic_attack_speed set to true makes players constantly attack at regular
# intervals regardless of other actions such as item (potion) use. This setting
# may cause high CPU usage with many players and potentially affect performance!
# force_monster_type_on_load server loads all monster types on startup for debugging purposes, you can change to false if all of your monster files don't throw errors to save up memory.
[misc]
allow_change_outfit = true              #(true or false)
free_premium = false                    #(true or false)
kick_idle_player_after_minutes = 15     #(>=0) minutes [15]
max_message_buffer = 4                  #(>0 or 0)
emote_spells = false                    #(true or false)
classic_equipment_slots = false         #(true or false)
classic_attack_speed = false            #(true or false)
show_scripts_log_in_console = true      #(true or false)
show_online_status_in_char_list = false #(true or false)
yell_minimum_level = 2                  #(>=0)
yell_always_allow_premium = false       #(true or false)
force_monster_type_on_load = true       #(true or false)
clean_protection_zones = false          #(true or false)

# Server Save
# NOTE: server_save_notify_duration in minutes
[server_save]
server_save_notify_message = true #(true or false)
server_save_notify_duration = 5   #(>=0) minutes [5]
server_save_clean_map = false     #(true or false)
server_save_close = false         #(true or false)
server_save_shutdown = true       #(true or false)

# Rates
# NOTE: rate_exp is not used if you have enabled stages in data/XML/stages.xml
[rates]
rate_exp = 5   #(>=0)
rate_skill = 3 #(>=0)
rate_loot = 2  #(>0 or 0)
rate_magic = 3 #(>=0)
rate_spawn = 1 #(>=0)

# Monsters
[monsters]
despawn_range = 2   #(>0 or 0)
despawn_radius = 50 #(>0 or 0)

# Stamina
[stamina]
stamina_system = true #(true or false)

# Scripts
# NOTE: script_vm_count set to 0 means number of logical cpus (or cgroup limit cpus)
[scripts]
warn_unsafe_scripts = true    #(true or false)
convert_unsafe_scripts = true #(true or false)
script_vm_count = 0           #(>0 || 0)

# Startup
# NOTE: default_priority only works on Windows and sets process
# priority, valid values are: "normal", "above-normal", "high"
[startup]
default_priority = "high"             #("normal" or "above-normal" or "high")
startup_database_optimization = false #(true or false)

#-- Status server information
[server_information]
owner_name = ""             #(text)
owner_email = ""            #(text)
url = "https://otland.net/" #(text)
location = "Sweden"         #(text)
